import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, Code2, Layers3, Workflow, Download } from "lucide-react";
import { Github, Linkedin } from "@/components/icons";
import { SystemCanvas } from "@/components/system-canvas";
import { ProjectCard } from "@/components/project-card";
import { profile, projects, experiences, education, certifications } from "@/data/portfolio";
const selectedSlugs = ["watermark-enterprise-automation", "qa-application", "multi-agent-research-automation", "boa-crm-integrations", "leadership-briefing-approval-automation", "geovision"];
const expertise = [
 { icon: Layers3, title: "Agentic AI & retrieval", description: "Build the path from context to action: grounded retrieval, specialized agents, structured outputs, and human review.", tools: ["LangGraph", "LangChain", "RAG", "Azure OpenAI", "Azure AI Search", "Copilot Studio", "Qdrant"] },
 { icon: Code2, title: "Software & data systems", description: "Turn architecture into working software, with API boundaries, query guardrails, browser testing, and observable delivery.", tools: ["Python", "FastAPI", "Node.js", "SQL", "PostgreSQL", "Azure Functions", "Playwright", "MCP", "Docker"] },
 { icon: Workflow, title: "Automation & integrations", description: "Connect business systems and make the handoffs dependable, from lead capture to attribution and approval workflows.", tools: ["n8n", "Zapier", "GoHighLevel", "Salesforce", "WhatConverts", "ClickUp", "REST APIs", "Webhooks"] },
];
export default function Home() {
 return <main id="main-content">
 <section className="hero shell" aria-labelledby="hero-heading">
  <div className="hero-meta"><span className="availability"><span className="signal-dot" /> OPEN TO AI & SOFTWARE ROLES</span><span className="mono hero-location">PAKISTAN · REMOTE WORLDWIDE</span></div>
  <div className="hero-grid"><div className="hero-copy"><p className="eyebrow">SYED MUHAMMAD REHAN / @RELINXX</p><h1 id="hero-heading">AI that works.<br /><span>Software<br />that lasts.</span></h1><p className="hero-description">I engineer AI agents, knowledge systems, and the software that connects them to real work. From architecture and APIs to evaluation, deployment, and handover.</p><div className="hero-actions"><a className="button button-primary" href="#work">Explore my work <ArrowDown size={17} aria-hidden="true" /></a><a className="button button-secondary" href={profile.resume} target="_blank" rel="noreferrer">Get résumé <Download size={16} aria-hidden="true" /></a></div><div className="hero-person"><Image src="/rehan-profile-suit.png" width={48} height={48} alt="Syed Muhammad Rehan" priority /><div><strong>Engineer. Builder. Systems thinker.</strong><span>Currently Senior Systems Automation Specialist at BOA</span></div></div></div><SystemCanvas /></div>
  <div className="hero-bottom"><span className="mono">BUILT TO CONNECT INTELLIGENCE WITH OPERATIONS</span><a href="#work">SCROLL TO EXPLORE <ArrowDown size={13} aria-hidden="true" /></a></div>
 </section>
 <section className="evidence-strip" aria-label="Evidence from delivered client work"><div className="shell evidence-grid"><div className="evidence-intro"><p className="eyebrow">ENGINEERING, WITH EVIDENCE</p><p>From a delivered enterprise AI engagement.</p></div><div><strong>20,934<span> records</span></strong><p>Indexed for knowledge retrieval</p></div><div><strong>3<span> databases</span></strong><p>Connected through guarded NL2SQL</p></div><div><strong>11 → 15<span> / 15</span></strong><p>Marked passes in a defined 15-case evaluation</p></div></div></section>
 <section className="section shell" id="work"><div className="section-heading"><div><p className="eyebrow"><span className="section-index">01 /</span> SELECTED WORK</p><h2>Ideas are easy.<br /><span>The build is the proof.</span></h2></div><p>Client delivery, agentic workflows, and software projects. Explore the problem, architecture, and what I owned in each build.</p></div><div className="project-grid">{selectedSlugs.map((slug, index) => { const project = projects.find(item => item.slug === slug); return project ? <ProjectCard key={slug} project={project} index={index} /> : null; })}</div><details className="more-projects"><summary>More from the engineering notebook <span>+ {projects.length - selectedSlugs.length} builds</span></summary><div>{projects.filter(p => !selectedSlugs.includes(p.slug)).map(p => <Link key={p.slug} href={`/projects/${p.slug}`}><span><strong>{p.title}</strong><small>{p.eyebrow}</small></span><ArrowUpRight size={19} /></Link>)}</div></details></section>
 <section className="experience-section" id="experience"><div className="section shell"><div className="section-heading"><div><p className="eyebrow"><span className="section-index">02 /</span> EXPERIENCE</p><h2>Ownership from<br /><span>first question to handover.</span></h2></div><p>I work across technical discovery, implementation, integration QA, and client communication. The details matter at every step.</p></div><div className="timeline">{experiences.map((job, index) => <article className="experience-row" key={job.company}><div className="experience-date"><span className="mono">{job.period}</span>{index === 0 && <span className="current-badge">CURRENT ROLE</span>}</div><div className="experience-company"><h3>{job.company}</h3><p>{job.role}</p><span>{job.location}</span></div><div className="experience-detail"><p>{job.summary}</p><ul>{job.highlights.map(point => <li key={point}>{point}</li>)}</ul></div></article>)}</div><div className="education-row"><p className="eyebrow">EDUCATION</p><div><h3>{education.school}</h3><p>{education.degree}</p></div><span className="mono">2022 — 2026</span></div></div></section>
 <section className="section shell" id="skills"><div className="section-heading"><div><p className="eyebrow"><span className="section-index">03 /</span> EXPERTISE</p><h2>Intelligence.<br /><span>Infrastructure. Integration.</span></h2></div><p>The stack changes with the problem. Clear boundaries, useful evaluation, and understandable systems stay constant.</p></div><div className="expertise-grid">{expertise.map((area, index) => <article className="expertise-card" key={area.title}><div className="expertise-top"><area.icon size={28} strokeWidth={1.3} aria-hidden="true" /><span className="mono">0{index + 1}</span></div><h3>{area.title}</h3><p>{area.description}</p><ul className="tag-list">{area.tools.map(tool => <li key={tool}>{tool}</li>)}</ul></article>)}</div><div className="approach"><span className="eyebrow">HOW I BUILD</span>{["Understand the workflow", "Design the boundaries", "Build & evaluate", "Deploy & document"].map((step, index) => <span key={step}><small>0{index + 1}</small>{step}{index < 3 && <ArrowUpRight size={14} aria-hidden="true" />}</span>)}</div><div className="credentials"><div><p className="eyebrow">CONTINUOUS LEARNING</p><h3>Credentials behind the craft.</h3></div><div className="credential-list">{certifications.map(cert => <a href={cert.credentialUrl} key={cert.title} target="_blank" rel="noreferrer"><span>{cert.title}<small>{cert.issuer} · {cert.completed}</small></span><ArrowUpRight size={17} aria-hidden="true" /></a>)}</div></div></section>
 <section className="contact-section" id="contact"><div className="shell contact-inner"><div><p className="eyebrow"><span className="signal-dot" /> AVAILABLE FOR THE NEXT BUILD</p><h2>Let’s build<br />something <em>useful.</em></h2><p>Exploring AI engineering, agentic AI, backend development, and systems automation roles. Remote worldwide or on-site in Pakistan. Full-time or contract.</p><a className="contact-email" href={profile.links.email}>{profile.email}<ArrowUpRight size={28} aria-hidden="true" /></a></div><div className="contact-links"><a href={profile.resume} target="_blank" rel="noreferrer">Download résumé <Download size={19} /></a><a href={profile.cv} target="_blank" rel="noreferrer">Download CV <Download size={19} /></a><a href={profile.links.github} target="_blank" rel="noreferrer">GitHub <Github size={19} /></a><a href={profile.links.linkedin} target="_blank" rel="noreferrer">LinkedIn <Linkedin size={19} /></a></div></div></section>
 </main>;
}
