import Image from "next/image";

export function WatermarkArchitecture({ compact = false }: { compact?: boolean }) {
  return <div className={`watermark-architecture ${compact ? "compact" : ""}`} aria-label="Separate knowledge retrieval and guarded analytics paths">
    <div className="architecture-lane"><p>01 / KNOWLEDGE</p><ol><li><strong>SharePoint</strong><span>Company content</span></li><li><strong>Azure AI Search</strong><span>Incremental indexing</span></li><li><strong>Copilot + Teams</strong><span>Grounded answers · citations</span></li></ol></div>
    <div className="architecture-lane"><p>02 / ANALYTICS</p><ol><li><strong>Business question</strong><span>Schema-aware routing</span></li><li><strong>Python validation</strong><span>Read-only · limits · retries</span></li><li><strong>3 Azure SQL sources</strong><span>Results through Teams</span></li></ol></div>
    <p className="architecture-footnote">Azure delivery · Key Vault · evaluation · technical handover</p>
  </div>;
}
export function ProjectEvidence({ slug }: { slug: string }) {
  if (slug === "watermark-enterprise-automation") return <section className="engineering-evidence" aria-labelledby="decisions-title">
    <p className="eyebrow">ENGINEERING DECISIONS</p><h2 id="decisions-title">Separate the retrieval path from the query path.</h2><WatermarkArchitecture />
    <div className="decision-grid"><article><h3>Two kinds of evidence</h3><p>Document questions need relevant passages and citations. Operational questions need schema selection, validated SQL, and bounded results. Separate paths make each system’s validation and failure boundaries explicit.</p></article><article><h3>Useful access, limited authority</h3><p>The analytics workflow uses read-only validation, table and column checks, row limits, timeouts, and correction retries. This supports business questions while restricting what generated queries can execute.</p></article></div>
    <div className="metric-context"><article><strong>20,934</strong><h3>Indexed records</h3><p>The recorded final Azure vector-index count. This is an index measure; it should not be interpreted as 20,934 unique source documents.</p></article><article><strong>11/15 → 15/15</strong><h3>Marked evaluation passes</h3><p>A defined 15-case evaluation improved during delivery. The public record does not include the question set, scoring rubric, or a separate unseen test set, so this is a bounded result.</p></article><article><strong>3 databases</strong><h3>Guarded analytics scope</h3><p>Schema-aware routing across three Azure SQL sources. The public Atlas demo uses synthetic SQLite data to illustrate the workflow separately.</p></article></div>
    <aside className="evidence-note">The public case study preserves architecture and recorded results. Client answers, database rows, and private evaluation material are not reproduced here.</aside>
  </section>;
  if (slug === "qa-application") return <section className="engineering-evidence">
    <p className="eyebrow">EXECUTION WALKTHROUGH</p><h2>A test is only useful when its result is visible.</h2>
    <Image className="evidence-screenshot" src="/projects/qa-agent-lab.png" alt="QA Agent Lab public authentication scenario interface" width={2560} height={1261} sizes="(max-width: 800px) 92vw, 1200px" />
    <ol className="control-flow"><li><strong>Goal</strong><span>Verify a valid user reaches the operations dashboard.</span></li><li><strong>Browser actions</strong><span>Inspect the fixed sandbox, interact with its form, and check navigation.</span></li><li><strong>Test artifact</strong><span>Generate and execute a Playwright specification.</span></li><li><strong>Result</strong><span>Expose the trace and assertions through the interface.</span></li></ol>
    <aside className="evidence-note"><strong>Demo check · 2 October 2026:</strong> the public interface loaded, but the run request failed to reach its worker. No successful execution is claimed for this check. The sequence above explains the intended flow; the repository documents the broader agent implementation.</aside>
    <div className="decision-grid"><article><h3>Public sandbox boundaries</h3><p>The hosted interface limits visitors to fixed sandbox origins and disposable Chromium sessions. It does not offer arbitrary browsing or require visitor credentials.</p></article><article><h3>Agent execution controls</h3><p>The source implementation includes bounded agent iterations, 60-second tool timeouts, a five-minute test limit, and a 1 MB generated-file limit. URL and file-path checks constrain inputs; failures need to remain visible rather than being counted as passing tests.</p></article></div>
  </section>;
  if (slug === "rag-evidence-studio") return <section className="engineering-evidence"><p className="eyebrow">IMPLEMENTATION VERSIONS</p><h2>One retrieval idea, two distinct versions.</h2><div className="decision-grid"><article><h3>Public source · Evidence Studio</h3><p>The linked repository implements TF-IDF retrieval with exact-term boosting over five technical documents and fifteen passages. Its evidence reader exposes ranked passages and citation references.</p></article><article><h3>Hosted interface · Watermarks RAG Desk</h3><p>The current deployment presents construction-document retrieval and describes vector retrieval with OpenAI answers. It has evolved beyond the linked source snapshot. Those backend details are deployment descriptions, not independently verified results from this review.</p></article></div><aside className="evidence-note">The architecture, stack, and corpus counts below refer to the public source prototype. The demo link opens the separately evolved Watermarks RAG Desk interface; it is not a public copy of the private Watermark client system.</aside></section>;
  if (slug === "natural-language-sql-agent") return <section className="engineering-evidence"><p className="eyebrow">PRODUCTION / PUBLIC DEMONSTRATION</p><h2>The same design concern, different data boundaries.</h2><div className="decision-grid"><article><h3>Client implementation</h3><p>Python, three Azure SQL databases, schema-aware routing, read-only validation, and Azure Functions / Bot Service delivery.</p></article><article><h3>Public Atlas demonstration</h3><p>Synthetic SQLite databases illustrate routing, validation, and execution. It contains no production client records and does not demonstrate a live connection to the three Azure SQL databases.</p></article></div></section>;
  const research = slug === "multi-agent-research-automation";
  if (research || slug === "leadership-briefing-approval-automation") return <section className="engineering-evidence"><p className="eyebrow">CONTROL POINT / ILLUSTRATED ROUTING</p><h2>{research ? "An inadequate draft takes the revision branch." : "A model recommendation does not grant approval."}</h2><ol className="control-flow"><li><strong>{research ? "Collect evidence" : "Normalize intake"}</strong><span>{research ? "Merge sources, deduplicate, and score." : "Check duplicates and required fields."}</span></li><li><strong>{research ? "Review draft" : "Analyze + validate"}</strong><span>{research ? "Evaluate the draft at the quality gate." : "Classify, extract, and check structure."}</span></li><li className="decision-node"><strong>{research ? "Below threshold?" : "Human decision"}</strong><span>{research ? "Route to revision, then review again." : "Approve / reject / revise / unknown."}</span></li><li><strong>{research ? "Validate + persist" : "Brief + audit"}</strong><span>{research ? "Deliver structured output through the success path." : "Record the decision and its controlled outcome."}</span></li></ol><p className="control-explanation">{research ? "The reviewer route gives the workflow a place to reject weak synthesis before delivery. Source fallbacks and a separate error path handle different failure modes; they do not substitute for the quality gate." : "Deterministic validation precedes human review. Revision and rejection have their own paths, so an ambiguous response is not treated as permission to proceed."} This diagram explains the workflow logic; it is not a captured execution result.</p></section>;
  return null;
}
